apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-client
  labels:
    app: python-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-client
  template:
    metadata:
      labels:
        app: python-client
    spec:
      containers:
      - name: python
        image: rudwns273/python-client:latest
        env:
        - name: TZ
          value: "Asia/Seoul"
      nodeSelector:
        topology.kubernetes.io/zone: ap-northeast-2a
